version: '3.4'

services:
  pgdata:
    container_name: pgdata
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=CatalogDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: